
baseURL = "www.siyanoku.com"
languageCode = "en-us"
title = "Siyanoku Trading Enterprise"
theme = "hugo-elate-theme"

[params]
  
  

  # Meta
  author = "Pantomath Application Division "
  description = "Keeping Our Promise"
  og_image = "/images/SiyaNoku1.png"
  email = "info@siyanoku.co.za"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  #googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = ""
    img = "SiyaNoku.png"
    home = ""
    work = ""
    testimonials = "Testimonials"
    services = ""
    about = ""
    contact = ""

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    [[menu.prepend]]
     url = "/home/"
     name = "Home"
     weight = 1
     pre = "external"


      # prepended links
    [[menu.prepend]]
     url = "/gallery/"
     name = "Gallery"
     weight = 2
     pre ="external"

      # prepended links
    [[menu.prepend]]
     url = "/home/"
     name = "Companies"
     weight = 2
     pre ="active"
     identifier = "services"
 
      # prepended links
    [[menu.prepend]]
     url = "/home/"
     name = "About"
     pre ="active"
     identifier = "about"
     weight = 3

      # prepended links
    [[menu.prepend]]
      url = ""
     name = "Contact Us"
     weight = 4
     pre ="active"
     identifier = "contact"

     [[menu.postpend]]
     url = "/home/"
     name = "Home"
     weight = 1
     


      # prepended links
    #[[menu.postpend]]
     #url = "/gallery/"
     #name = "Gallery"
     #weight = 2
     

      # prepended links
    [[menu.postpend]]
     url = "/home/"
     name = "Companies"
     weight = 3

      # prepended links
    [[menu.postpend]]
     url = "/home/"
     name = "About"
     weight = 4

      # prepended links
    [[menu.postpend]]
      url = "/home/"
     name = "Contact Us"
     weight = 5
     

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    

  # Hero section
  [params.hero]
    title = "Siyanoku Trading Enterprise"
    subtitle = 'Keeping our promise'
  # Video
    #[params.visual.video]
      enable = true
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9u"

    
    
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  

  [[params.intro.item]]
    title = "Vision"
    description = "To be a supplier of choice in the built and maintenance programme in the continent  that contribute in reducing unemployment, providing platform for empowerment and exposure to the women, youth and people with disabilities."
    url = "#"
    #button = "View"
    #icon = "icon-wrench"
    icon = "icon-building-o"
    img = "green-card.jpg"

  [[params.intro.item]]
    title = "Mission"
    description = "The business mission is to exploit the localisation programmes to build a formidable supplier company that participate meaningfully within the built industry to create job opportunities, especially for women, youth and people with disability, maximise its profit margins."
    url = "#"
    #button = "view"
    icon = "icon-bulb"
    img = "green-card.jpg"

  [[params.intro.item]]
    title = "Value"
    description = "Siyanoku Trading Enterprise is guided by the following ideals or values:	integrity, honesty, professionalism, mutualism, life learning and timeous in quality delivery and interventions                          "
    url = "#"
    #button = "View"
    #icon = "icon-wrench"
    icon = "icon-grid"
    img = "green-card.jpg"

  

 
  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = ""

    [[params.testimonials.item]]
      quote = ""
      person = ''
      img = ""
      alt = ""
    
  # Services section
  [params.services]
    enable = true
    title = "Our Companies"
    description = "We also offer other services within our other companies."

    [[params.services.item]]
      title = "Siyanoku Plant Hire"
      description = "Heavy Machinery"
       icon = "icon-gear"
    [[params.services.item]]
      title = "Siyanoku Energy"
      description = "Diesel/Diesel tank cleaning, Renewable energy"
       icon = "icon-energy"

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = ""
    

    [[params.work.row]]
      img = "SN1.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""

    
      
      

  # Work2 section
  [params.work2]
    enable = true
    title = "Gallery"
    description = ""
    

    [[params.work2.row]]
      img = "SN1.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""

    [[params.work2.row]]
      img = "SN2.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""

    [[params.work2.row]]
      img = "SN3.jpg"
      alt = "Image3"
      title = ""
      subtitle = ""

    [[params.work2.row]]
      img = "SN4.jpg"
      alt = "Image4"
      title = ""
      subtitle = ""

    [[params.work2.row]]
      img = "SN5.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""

      [[params.work2.row]]
      img = "SN6.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
      
      [[params.work2.row]]
      img = "SN7.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
      [[params.work2.row]]
      img = "SN8.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
      [[params.work2.row]]
      img = "SN9.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
      

      [params.work3]
    enable = true
    title = "Gallery"
    description = " "
    

    [[params.work3.row]]
      img = "SN1.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""

    [[params.work3.row]]
      img = "SN2.jpg"
      alt = "Image2"
      title = ""
      subtitle = ""

    [[params.work3.row]]
      img = "SN3.jpg"
      alt = "Image3"
      title = ""
      subtitle = ""

      [[params.work3.row]]
      img = "SN4.jpg"
      alt = "Image4"
      title = ""
      subtitle = ""

    [[params.work3.row]]
      img = "SN5.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""

      [[params.work3.row]]
      img = "SN6.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
   
      [[params.work3.row]]
      img = "SN7.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
      [[params.work3.row]]
      img = "SN8.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""
      [[params.work3.row]]
      img = "SN9.jpg"
      alt = "Image5"
      title = ""
      subtitle = ""

   
      
  # About section
  [params.about]
    enable = true
    title = "About"
    description = " We are a business registered as a close corporation and totally dedicated to affirmative action and 100% commitment to our work. Care is taken to ensure that all personnel employed comply with the necessary requirements and high standard that the Siyanoku Trading Enterprise clients requires."

   [[params.about.item]]
      name = "Ms Bridget Ndlovu"
      position = "Director"
      description = "Founder of Siyanoku Trading Enterprise"
      # img = "person4.jpg"
      # alt = "Person2"
      # social = [ ]
      

        

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "with us "
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-building-o", "Khokhamoya Industrial Park, Portion 10"],
        ["", " ERF  548 Rocky's Drift, Ext 10 White River, 1240"],
        ["icon-phone", "(013) 591-2783"],
        ["icon-envelope", "info@siyanoku.co.za"],
        
      ]

    name = "Name*"
    email = "Email*"
    company = "Contact Company e.g Plant Hire"
    machine = "Machinery"



    

    message = "Message*"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Siyanoku Trading Enterprise All Rights Reserved. <br>Developed by Zubery Pty Ltd'
    links = [
        
      ]